---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-workflow-kmambo-io-v1alpha1-task
  failurePolicy: Fail
  name: vtask.kb.io
  rules:
  - apiGroups:
    - workflow.kmambo.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tasks
  sideEffects: None
