---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - workflow.kmambo.io
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflow.kmambo.io
  resources:
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - workflow.kmambo.io
  resources:
  - tasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workflow.kmambo.io
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflow.kmambo.io
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - workflow.kmambo.io
  resources:
  - workflows/status
  verbs:
  - get
  - patch
  - update
