apiVersion: workflow.kmambo.io/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: task
    app.kubernetes.io/instance: task-sample
    app.kubernetes.io/part-of: kmambo-workflows
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kmambo-workflows
  name: task-sample
spec:
  # TODO(user): Add fields here
