apiVersion: workflow.kmambo.io/v1alpha1
kind: Workflow
metadata:
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/instance: workflow-sample
    app.kubernetes.io/part-of: kmambo-webhooks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kmambo-webhooks
  name: workflow-sample
spec:
  # TODO(user): Add fields here
